# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: trusty 
language: cpp 
compiler:
  - gcc
notifications:
  email:
    on_success: never
    on_failure: never
#    recipients:
#      - shaotu.jia
env:
  matrix:
    - USE_DEB=true  ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true  ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

matrix:
  allow_failures:
    - env: USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - env: USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
  - docker run apt-get install -y lcov
script: 
  - source .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script

# Generate code coverage, other artifacts
# ---------------------------------------
  - WORKDIR /root/catkin_ws/build
  - RUN lcov --directory . --capture --output-file coverage.info
  - RUN lcov --remove coverage.info '/opt/*' '/usr/*' '*/devel/*' '*test_*' '*_test*' --output-file coverage.info
  - RUN lcov --list coverage.info
  - RUN coveralls-lcov coverage.info
